[build]
  publish = "media"
  command = "npm install && npm run build"  # Install dependencies before build



[[redirects]]
  from = "/media/journal_images/*"
  to = "/media/journal_images/:splat"
  status = 200
  force = true
