[build]
  command = "cd netlify/functions && npm install && npm run build"
  publish = "media"




[[redirects]]
  from = "/media/journal_images/*"
  to = "/media/journal_images/:splat"
  status = 200
  force = true
